// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// This file is generated by LogCategoryGenerator
// To add new categories, use Tools -> Logger -> Category Manager

namespace Azen.Logger
{
    public enum LogCategory
    {
        None = 0,
        Analytics = 1,
        Audio = 2,
        Error = 3,
        FrequencyManager = 4,
        Gameplay = 5,
        Input = 6,
        Network = 7,
        Other = 8,
        Performance = 9,
        PMG = 10,
        System = 11,
        UI = 12,
        Warning = 13
    }
}
